### ISSUE TITLE
右カラムのリンクにYouTubeがない

### ISSUE THREAD

**Issue by forno** [Amplent/MomohoshiManaka#1]
![image](https://user-images.githubusercontent.com/11057257/66264423-ebe8d880-e83f-11e9-86d8-1fc3dba08baa.png)

行われている動画がまとまっており大変見やすく感服いたしました

さて，右カラムに桃星にかかわるリンクが現在3種ありますが，ShowroomがあるならYouTubeのリンクも追加していただければ見やすくなるかと存じます
ご検討くださいませ

**Comment by LiamKanon** [comment]
ご指摘いただきありがとうございます！
仰るとおり、Youtubeのリンクを追加させていただきます！

**Comment by LiamKanon** [comment]
リンク追加いたしました！
![youtube](https://user-images.githubusercontent.com/54920879/66264608-52bbc100-e843-11e9-888b-2f7e30d3b5e7.png)

**Comment by forno** [comment]
早い！
