### ISSUE TITLE
桃星愛花用語集を作る

### ISSUE THREAD

**Issue by forno** [Amplent/MomohoshiManaka#2]
https://twitter.com/manachan_momo/status/1180684781689831425

**Comment by LiamKanon** [comment]
1. 用語の収集
2. 用語の定義
3. レイアウト・デザインラフ

用語の選定から始めます……！！

**Comment by forno** [comment]
いぬはっか氏より，エア桃星のデータを頂きました

> いっっちばん美味しそうなハラミを最後に残すの。それがハラミデザート選手権。
牛タンのレモンは網に塗るためにあるんだよ、実は。
ロリィタと…メイドは…違うんだよ…！
焼肉とステーキを一緒にする人は母体からやり直してきて
おしりかわいい～
フルーツ食べないけど、フルーツ柄のお洋服は好き。
じゃあおつも切っていきまーす。[USER]さんからね。
明日学校の人もお仕事の人も社会の闇に負けずに頑張ってください！お休みの人は泥のように寝てください！
大丈夫。まだオギャる時ではない。
趣味は焼肉です。特技は焼肉です。将来の夢は焼肉屋さんのバーチャルキャンペーンガールになることです。
あ、ごはん炊けました。元気なごはんですよ～。
あ、ごめん今日ごはん炊けないの。
またくしゃみで人を救ってしまった…
行くぞ行くぞ行くぞ行くぞ
あ、[USER]さんもこんも～！お越しいただきありがとうございます！
ほーん。完璧に理解した。
くしゃみ出なかった～…
あーそれ好き。[LIST2]点。　（※16～24点でランダム）
…うーん…[LIST3]点。　（※3～9点でランダム）
コンビニスイーツってだいたいロールケーキ買っちゃわない？
食べることは、生きること。ご飯楽しいよな。
あれ？[USER]さん言ったっけ…？言ってない気がする！こんも！
レジ前にあるチロルチョコとか絶対買っちゃう。
ほぉ～ん…？ぶち壊せばいいってこと？
いける。真剣にやる。まかせな。
大丈夫。いま無敵だから。
中島みゆきの声めっちゃ出しやすいんだよね。わたし実質中島みゆきかもしんない。
桃星愛花-まなちゃんねる「待機えらーい!!」
来月号の幼稚園めっちゃ楽しみなんだけど！
人間は欲深い生き物だから。人類は愚か。
桃星愛花-まなちゃんねる「本日もたくさんお越しいただきありがとうございました!!」
フエェェッックッ ヒャーーーーッッ！！（※くしゃみ）
あ、わかった。頭いいから。
わたし天才。伸び代しかない。
お金が嫌いな人間とかおらんやろ。
ぶぅ～～～ん！！！…ごめんバイク通った。
腕のふくらはぎがパンパンになっちゃう！
今日も本当にお仕事・学校とってもお疲れ様でした！
カロリー美味しいじゃん。カロリー美味しくなかったことある？
へぇ～…ラーメンってスポーツなんだ…
ししゃもってトビウオの下等種族なの？
びんちょうってマグロの下等種族なの？
どこだ？どこ？どこどこどこどこ
ねぇ見て！これ見て！みてみてみてみて
視覚的な可愛さで殴れるようになりたい。可愛さはパワー。
大人ってかわいそう…
ぱぱ～ぱ ぱぱぱ♪ ぱぱ～ぱ ぱぱぱ♪ ぱぱぱぱぱ♪～～ぱぱ↑～～ぱぱ↑↑～～♪
ちょっとバーチャルな動きしまーす
一番好きな食べ物は焼肉だけど、残りの4本指に入るくらい鶏皮が好き。パリパリは正義。
もっとタマネギを炒めつける必要がある…
ヤギの目って怖くない？なんであんなマイナスドライバーみたいな目してんの？
これは腕じゃないほうのふくらはぎ。足のふくらはぎ。
これが大人のやり方か…！
牡蠣は凝縮された海。ブロッコリーは凝縮された森。
ぐちゃぐちゃになったタマネギとー、しおしおになったホウレン草とー、カチコチになったブドウは食べれるの。
来世の夢はタコになることだったんだけど、泳げないから諦めた。
これはね、ハート。そう。あくまでもハート。　（※ガチイベ中か否かでケツ叩き系と入れ替え）
きれいな緑のダルマだねー。まるでカッパの皮膚のようないい緑だ。
親に似て凛々しいダルマだね。100つ子さん出産おめでとう。
血のように鮮やかな赤いダルマだね。ヘモグロビンの色だあ。
おー、これは。黄ばんだいいダルマだねぇ。
あの晴れ渡った空のような美しい青いダルマだね。
河童って淡水魚じゃないの？
[LIST4]わかる。[LIST5]わかる。[LIST6]わかる。わかるわかるわかる。　（※褒め言葉一覧からランダム）
>
> ↓褒め言葉一覧
すごい
えらい
つよい
上手い
さすまな
天才
冴えてる
できる子
ないすぅ
勘がいい
>
> ↓最近あんまり言わなくなったから外したやつ
>
> ビスケットって焼きたてにしてくれるの！？10分くらいなら全然待つ！！！（※ケンタッキー）
桃星閉じ込められがちだし一人じゃ出れない。（脱出ゲームをやりながら）
三周は無理せず無理してほしい。
サイゼリヤのアイスってガッチガチで出てこない？
ミラノ風ドリアの端っこのカリカリしたとこ好き。
そこそこ良いかな…くらいのものだったらこんなに熱く語らないからね。
オギャりそう～
私の枠で寝落ちできるのレベル高いよね
人間証明たすかる～
不二家のミルキーソフトは機械を洗浄した翌日くらいが一番美味しい。
理解及ばず無念…！
野生のお金めっちゃ活きがいいよね　（※マリオオデッセイの束コイン）
顔でかい生き物はだいたい怖いよね。怖くない？　（※ワンワン）

**Comment by LiamKanon** [comment]
辞書式にして各ページ用意する→工数やばめなので見送り
名言集形式にして引用風＆引用元を掲載→現実的な落とし所
↑引用元引っ張ってこれるか自信がないのでとりあえず名言風に斜体でまとめてみますー！！

**Comment by forno** [comment]
用語集の作成という意味では終わっているのでClose
