### ISSUE TITLE
まなかとながめし用語集との連携

### ISSUE THREAD

**Issue by forno** [Amplent/MomohoshiManaka#3]
https://twitter.com/djk_eso/status/1185724140998672389?s=20

![image](https://user-images.githubusercontent.com/11057257/67155036-b2d15d80-f341-11e9-97f4-b395fec3727b.png)

けそさんとの連携

**Comment by forno** [comment]
可能性の検討の意でIssueあげです～

**Comment by forno** [comment]
仕様としては，「文言」と「どういう場面で使われるか」の情報セットになります

**Comment by forno** [comment]
けそさん側からの利用許諾でました

![image](https://user-images.githubusercontent.com/11057257/67155074-ea8cd500-f342-11e9-84e6-3e445dd8147c.png)

https://twitter.com/djk_eso/status/1185783737516060674?s=20

**Comment by LiamKanon** [comment]
ありがとうございます！！！！！！
早速作業に取り掛かります！！！！

**Comment by forno** [comment]
連絡のとりありやどういう形で連携するかなどの調節はお任せいたします(*- -)(*_ _)ペコリ

ありがとうございます！

**Comment by forno** [comment]
ひとまず実装完了
